name: Lint

on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Set up toolchain via mise (node, nub, rust)
        uses: jdx/mise-action@v5.0.1

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

  rustfmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Set up toolchain via mise (node, nub, rust)
        uses: jdx/mise-action@v5.0.1

      - name: Run cargo fmt
        run: cargo fmt --all -- --check
